name: "New Dataset"
description: Add a new dataset to the EM Database
title: "[New Dataset]: "
labels:
  - "new_dataset"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for adding a new dataset to the EM Database! Please fill out the following
        form regarding the dataset you are submitting. Make sure to include as much relevant
  - type: input
    id: dataset_name
    attributes:
      label: --Dataset Name--
      description: Please provide a short name for the dataset you are submitting. This will be used as the identifier for the dataset in the database so short and descriptive is best.
      placeholder: ex. MgONanocrystals
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: --Author--
      description: What is your name?
      placeholder: ex. Jane Doe
    validations:
      required: true
  - type: input
    id: affiliation
    attributes:
      label: --Affiliation--
      description: Which institution or company are you at?
      placeholder: ex. University of Wisconsin-Madison
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: --URL--
      description: Please provide a URL where the dataset can be downloaded. This must be a direct link to the file itself - the file name is taken from the end of it.
      placeholder: ex. https://zenodo.org/records/15490547/files/smallPtychography.hspy
    validations:
      required: true
  - type: input
    id: checksum
    attributes:
      label: --Checksum--
      description: Please provide the checksum of the dataset file for verification purposes. Include the type of checksum (e.g., md5, sha256) followed by the checksum value.
      placeholder: ex. md5:df9376d5c020a23f0f7f51cfe79f303f
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: --Description--
      description: Please provide a brief description of the dataset you are submitting. Include details such as the technique used, the sample type, and any other relevant information.
      placeholder: ex. A 4D STEM dataset of various MgO nanocrystals
    validations:
      required: true
  - type: input
    id: detector_manufacturer
    attributes:
      label: --Detector Manufacturer--
      description: Please provide the manufacturer of the detector used to acquire the dataset.
      placeholder: ex. Direct Electron
    validations:
      required: false
  - type: input
    id: detector_model
    attributes:
      label: Detector Model
      description: Please provide the model of the detector used to acquire the dataset.
      placeholder: ex. DE-16
    validations:
      required: false
  - type: input
    id: microscope_vendor
    attributes:
      label: Microscope Vendor
      description: Please provide the vendor of the microscope used to acquire the dataset.
      placeholder: ex. Thermo Fisher Scientific
    validations:
      required: false
  - type: input
    id: microscope_model
    attributes:
      label: Microscope Model
      description: Please provide the model of the microscope used to acquire the dataset.
      placeholder: ex. Gen 1 Titan
    validations:
      required: false
  - type: input
    id: accelerating_voltage
    attributes:
      label: Accelerating Voltage
      description: Please provide the accelerating voltage used to acquire the dataset (in kV).
      placeholder: ex. 200 kV
    validations:
      required: false
  - type: input
    id: license
    attributes:
      label: Dataset License
      description: Please provide the license under which the dataset is released.
      placeholder: ex. CC-BY-4.0
    validations:
      required: true
  - type: dropdown
    id: technique
    attributes:
      label: Technique
      description: Select the technique used to acquire the dataset.
      options:
        - 4D-STEM
        - EELS
        - EDS
        - EBSD
        - STEM
        - In-situ TEM
        - Cryo-EM
        - Other
  - type: input
    id: tags
    attributes:
      label: Tags
      description: Please provide relevant tags for the dataset, separated by commas.
      placeholder: ex. Orientation Mapping, Nanocrystals, Ptychography, Strain Mapping
    validations:
      required: false